### ISSUE TITLE
Is the mailing list dead?

### ISSUE THREAD

**Issue by FBergeron** [cleitet/wpkg-gp#122]
Last weekend, I tried to submit a question to the mailing list (wpkg-users@lists.wpkg.org).  I got this reply:

Sorry, we were unable to deliver your message to the following address.
<wpkg-users@lists.wpkg.org>:
Unable to deliver message after multiple retries, giving up.

Also, I noticed that the last message in the archive dates from April, 5th 2019. That's a bit old.

I'm wondering if there is an issue with the mailing list...  
Is everything in order or is it just me?
Should I post my issue here instead?

Regards.

**Comment by adelphi-company** [comment]
I had the same problem. It seems that the WPKG website and mailing lists are no longer maintained for several month now...

**Comment by FBergeron** [comment]
That's sad.  Hopefully, someone else will take over the project eventually.  Thanks for your message.
